import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { locales } from "@/i18n";
import { unstable_setRequestLocale } from "next-intl/server";
import Link from "next/link";
import { ApolloWrapper } from "../ApolloWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Generate static paths based on locale params
export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}) {
  unstable_setRequestLocale(locale);

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <ApolloWrapper>
          <nav className="flex justify-between gap-3 px-24 py-3">
            <Link href={`/${locale}`}>Go Home</Link>
            <div className="flex gap-3">
              {locales.map((language) => (
                <Link key={language} href={`/${language}`}>
                  {language === locale ? <strong>{language}</strong> : language}
                </Link>
              ))}
            </div>
          </nav>
          {children}
        </ApolloWrapper>
      </body>
    </html>
  );
}
