import Logo from "@/components/Logo";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Link from "next/link";
import "../globals.css";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { getTranslations, setRequestLocale } from "next-intl/server";

// TODO: add license for the fonts
// Font display
const aujournuit = localFont({
  src: "../../../public/fonts/Aujournuit-Condensed.woff2",
  variable: "--font-aujournuit",
  display: "swap",
});

// TODO: add license for the fonts
// Font main
const ronzino = localFont({
  src: [
    {
      path: "../../../public/fonts/Ronzino-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../../public/fonts/Ronzino-Oblique.woff2",
      weight: "400",
      style: "italic",
    },
    {
      path: "../../../public/fonts/Ronzino-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../../public/fonts/Ronzino-MediumOblique.woff2",
      weight: "500",
      style: "italic",
    },
    {
      path: "../../../public/fonts/Ronzino-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../../public/fonts/Ronzino-BoldOblique.woff2",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-ronzino",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  setRequestLocale(locale);
  const t = await getTranslations("layout");

  return (
    <html lang={locale}>
      <body
        className={`${aujournuit.variable} ${ronzino.variable} flex min-h-svh flex-col bg-orange-50 font-ronzino text-blue-900 dark:bg-black dark:text-orange-50`}
      >
        <NextIntlClientProvider>
          <header className="relative z-30 mx-auto flex h-16 w-full max-w-container2560 shrink-0 items-center px-4 py-2">
            <nav className="flex flex-1 font-medium ">
              <ul className="relative flex flex-grow items-center gap-4">
                <li className="mr-auto flex items-center gap-4">
                  <Link
                    href={`/${locale}`}
                    className="flex items-center gap-3 leading-none"
                    aria-label="Sandra savorgnani home"
                  >
                    Sandra Savorgnani
                  </Link>
                </li>
                <li>
                  <Link href={`/${locale}/works`}>{t("header.works")}</Link>
                </li>
                <li>
                  <Link href={`/${locale}/about`}>{t("header.info")}</Link>
                </li>
              </ul>
            </nav>
          </header>
          <div className="flex-1 shrink-0">{children}</div>
          <footer className="relative flex min-h-16 w-full max-w-container2560 shrink-0 flex-col items-center justify-center px-4 py-2 lg:flex-row lg:justify-between">
            <Link
              href={`/${locale}`}
              className="mb-2 flex items-center lg:mb-0"
            >
              <Logo />
            </Link>
            {/* FIXME: create these pages */}
            <div className="flex items-center gap-2 text-sm">
              <Link href={`/${locale}/legal`}>{t("footer.legal")}</Link>|
              <Link href={`/${locale}/privacy`}>{t("footer.privacy")}</Link>|
              <Link href={`/${locale}/credit`}>{t("footer.credit")}</Link>
            </div>
            {/* <div className="flex gap-3">
            {locales.map((language) => (
              <Link key={language} href={`/${language}`}>
                {language === locale ? <strong>{language}</strong> : language}
              </Link>
            ))}
          </div> */}
          </footer>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
